# -*- coding: utf-8 -*-
"""chat_memory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqtA9zlqmMs9046ribgKI1BckZLKzCVY
"""

from collections import deque

class ChatMemory:
    def __init__(self, max_turns=5):
        self.buffer = deque(maxlen=max_turns * 2)  # user + assistant per turn

    def add_turn(self, user_input, assistant_response):
        self.buffer.append(f"User: {user_input}")
        self.buffer.append(f"Assistant: {assistant_response}")

    def add_user_input(self, user_input):
        self.buffer.append(f"User: {user_input}")

    def build_prompt(self, system_instruction):
        conversation = "\n".join(self.buffer)
        return f"{system_instruction}\n{conversation}\nAssistant:"