# -*- coding: utf-8 -*-
"""model_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19abm6xhcIc7ekOhFY_Gsz8jug_ViOV3k
"""

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from transformers.utils import logging
import torch

# Suppress download and model logs
logging.set_verbosity_error()

def load_chatbot_pipeline(model_id="TinyLlama/TinyLlama-1.1B-Chat-v1.0"):
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.float32,
        trust_remote_code=True
    )

    return pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        max_new_tokens=100,
        do_sample=False,
        temperature=0.0
    )